version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Yekaterinburg'
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      fonts:
        patterns:
          - '@fontsource/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Yekaterinburg'
    open-pull-requests-limit: 3
