name: Mirror to Gitflic

on:
  push:
    branches: ['**']
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Push mirror to Gitflic
        env:
          GITFLIC_TOKEN: ${{ secrets.GITFLIC_TOKEN }}
        run: |
          git config --global credential.helper '!f() { echo "username=shkrndns"; echo "password=${GITFLIC_TOKEN}"; }; f'
          git push --mirror "https://gitflic.ru/project/shkrndns/white_anrotrip.git"
